{
  wayland.windowManager.hyprland.settings = {
    bind = [
      "$mod, Return, exec, kitty"
      "$mod, W, exec, vivaldi"
      "$mod, Q, killactive"
      "$mod, F, fullscreen"
      "ALT, L, exec, hyprlock"
      "$mod SHIFT, left, movewindow, l"
      "$mod SHIFT, right, movewindow, r"
      "$mod SHIFT, up, movewindow, u"
      "$mod SHIFT, down, movewindow, d"
      "$mod SHIFT, h, movewindow, l"
      "$mod SHIFT, l, movewindow, r"
      "$mod SHIFT, k, movewindow, u"
      "$mod SHIFT, j, movewindow, d"
      "$mod ALT, left, swapwindow, l"
      "$mod ALT, right, swapwindow, r"
      "$mod ALT, up, swapwindow, u"
      "$mod ALT, down, swapwindow, d"
      "$mod ALT, h, swapwindow, l"
      "$mod ALT, l, swapwindow, r"
      "$mod ALT, k, swapwindow, u"
      "$mod ALT, j, swapwindow, d"
      "$mod, left, movefocus, l"
      "$mod, right, movefocus, r"
      "$mod, up, movefocus, u"
      "$mod, down, movefocus, d"
      "$mod, h, movefocus, l"
      "$mod, l, movefocus, r"
      "$mod, k, movefocus, u"
      "$mod, j, movefocus, d"
      "$mod, 1, workspace, 1"
      "$mod, 2, workspace, 2"
      "$mod, 3, workspace, 3"
      "$mod, 4, workspace, 4"
      "$mod, 5, workspace, 5"
      "$mod, 6, workspace, 6"
      "$mod, 7, workspace, 7"
      "$mod, 8, workspace, 8"
      "$mod, 9, workspace, 9"
      "$mod, 0, workspace, 0"
      "$mod SHIFT, SPACE, movetoworkspace, special"
      "$mod, SPACE, togglespecialworkspace"
      "$mod SHIFT, 1, movetoworkspace, 1"
      "$mod SHIFT, 2, movetoworkspace, 2"
      "$mod SHIFT, 3, movetoworkspace, 3"
      "$mod SHIFT, 4, movetoworkspace, 4"
      "$mod SHIFT, 5, movetoworkspace, 5"
      "$mod SHIFT, 6, movetoworkspace, 6"
      "$mod SHIFT, 7, movetoworkspace, 7"
      "$mod SHIFT, 8, movetoworkspace, 8"
      "$mod SHIFT, 9, movetoworkspace, 9"
      "$mod SHIFT, 0, movetoworkspace, 10"
      "$mod CONTROL, right, workspace, e+1"
      "$mod CONTROL, left, workspace, e-1"
      "ALT, Tab, cyclenext"
      "ALT, Tab, bringactivetotop"
    ];
  };  
}
